@startuml

skinparam linetype ortho

class BazarDriver

package Controllers {
    class Store

    class PurchaseManager

    class IData
}

package Models {
    abstract class Device <<abstract>>

    class Printer

    class Computer

    abstract class Purchase <<abstract>>

    class inStorePurchase

    class OnlinePurchase
}

package Utility {
    class MenuInput

    class Utils

    enum PurchaseType <<enum>>
}


Printer -u-|> Device
Computer -u-|> Device

Printer "*" ---> "1" Store : creates
Computer "*" ---> "1" Store : creates

Printer ...> Utils : uses
Computer ...>  Utils : uses

BazarDriver "1" .u.> "1" Store
BazarDriver ...> MenuInput

BazarDriver "1" ---> "1" PurchaseManager

PurchaseManager --> Purchase : creates
PurchaseManager ...> IData : uses

@enduml