@startuml

class BazarDriver {

}

class Store {

}

class Printer {

}

class Computer {

}

class Device {

}

Printer -u-|> Device
Computer -u-|> Device

Printer "2" -r-* "1" Store : creates <
Computer "3" -l-* "1" Store : creates <

BazarDriver "1" .u.> "1" Store : creates >



@enduml